Update plot_wingbox.py
Commented out line 67
self.ax.set_aspect('equal')
when running plot_wingbox aerostruct.db as recommended in the wingbox_mpt_Q400_example.py file this would cause an error.

Traceback (most recent call last):
  File "C:\Users\EricMarc-Aurele\Anaconda3\Scripts\plot_wingbox-script.py", line 11, in <module>
    load_entry_point('openaerostruct', 'console_scripts', 'plot_wingbox')()
  File "c:\users\ericmarc-aurele\openaerostruct\openaerostruct\utils\plot_wingbox.py", line 900, in disp_plot
    disp = Display(args)
  File "c:\users\ericmarc-aurele\openaerostruct\openaerostruct\utils\plot_wingbox.py", line 67, in __init__
    self.ax.set_aspect('equal')
  File "c:\users\ericmarc-aurele\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

Commenting the line allows the wing box optimization to be displayed.

I have NOT done testing to determine if this will cause problems elsewhere.